---
version: '3.8'
services:
  memcached:
    image: memcached:latest
    ports:
      - "11211"
  redis:
    image: redis:latest
    ports:
      - "6379"
  redis-admin:
    image: erikdubbelboer/phpredisadmin
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: redis
      TZ: ${TZ-America/Sao_Paulo}
    ports:
      - "8084:80"
networks:
  default:
    name: pratica2
