---
version: '3.8'

services:
  primary:
    hostname: 'primary'
    image: crunchydata/crunchy-postgres:centos8-13.6-4.7.5
    environment:
      - PGHOST=/tmp
      - MODE=postgres
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=primary
      - PG_PRIMARY_USER=postgres
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=testdb
      - PG_USER=testuser
      - PG_PASSWORD=password
      - PG_ROOT_PASSWORD=password
      - PG_PRIMARY_PORT=5432
      - LOG_STATEMENT=all
      - LOG_MIN_DURATION_STATEMENT=0
      - CRUNCHY_DEBUG=true
    volumes:
      - pg-primary-vol:/pgdata
    ports:
      - "5432"
      - "5480:5432"
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
          - node.role == worker
  replica1:
    hostname: 'replica1'
    image: crunchydata/crunchy-postgres:centos8-13.6-4.7.5
    environment:
      - PGHOST=/tmp
      - MODE=postgres
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=replica
      - PG_PRIMARY_HOST=primary
      - PG_PRIMARY_PORT=5432
      - PG_PRIMARY_USER=postgres
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=testdb
      - PG_USER=testuser
      - PG_PASSWORD=password
      - PG_ROOT_PASSWORD=password
      - LOG_STATEMENT=all
      - LOG_MIN_DURATION_STATEMENT=0
      - CRUNCHY_DEBUG=true
    volumes:
      - pg-replica1-vol:/pgdata
    ports:
      - "5432"
      - "5481:5432"
    deploy:
      placement:
        constraints:
          - node.labels.type != primary
          - node.role == worker
  replica2:
    hostname: 'replica2'
    image: crunchydata/crunchy-postgres:centos8-13.6-4.7.5
    environment:
      - PGHOST=/tmp
      - MODE=postgres
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=replica
      - PG_PRIMARY_HOST=primary
      - PG_PRIMARY_PORT=5432
      - PG_PRIMARY_USER=postgres
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=testdb
      - PG_USER=testuser
      - PG_PASSWORD=password
      - PG_ROOT_PASSWORD=password
      - LOG_STATEMENT=all
      - LOG_MIN_DURATION_STATEMENT=0
      - CRUNCHY_DEBUG=true
    volumes:
      - pg-replica2-vol:/pgdata
    ports:
      - "5432"
      - "5482:5432"
    deploy:
      placement:
        constraints:
          - node.labels.type != primary
          - node.role == worker
networks:
  default:
    name: app
    external: true

volumes:
  pg-primary-vol:
  pg-replica1-vol:
  pg-replica2-vol: