version: '3.8'
services:
  app:
    image: php:8.1-cli
    ports:
      - "8060:80"
    volumes:
      - ./:/opt/project:rw
    working_dir: /opt/project
    command: php -S 0.0.0.0:80 -t public
  memcached:
    image: memcached
networks:
  default:
    name: pratica2
