---
version: '3.8'

services:
  php-cli:
    image: cloud.canister.io:5000/fperrony/php-cli-dev:8.1
    volumes:
      - ./:/opt/project
      - ./../domain:/opt/domain
    user: ${FCPLUSER-root}
    working_dir: /opt/project
    environment:
      TZ: ${TZ-America/Sao_Paulo}
  php-test:
    image: cloud.canister.io:5000/fperrony/php-cli-dev:8.1
    volumes:
      - ./:/opt/project
      - ./../domain:/opt/domain
    user: ${FCPLUSER-root}
    working_dir: /opt/project
    environment:
      TZ: ${TZ-America/Sao_Paulo}
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t public
networks:
  default:
    name: app
    external: true